import { PublicKey, LAMPORTS_PER_SOL } from "@solana/web3.js";
import { AnchorProvider, Program, BN } from "@coral-xyz/anchor";
import { PROGRAM_ID, SPRKS_DECIMALS_MULTIPLIER, TIERS } from "@/config/sprks";
import SparksPresaleIdl from "../../anchor/target/idl/sparks_presale.json";

// ─── IDL — generated by `anchor build` (source of truth) ─────────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const IDL = SparksPresaleIdl as any;

// ─── PDA Helpers ──────────────────────────────────────────────────────────────

export function getPresaleStatePDA(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("presale_state")],
    PROGRAM_ID
  );
}

export function getTokenVaultPDA(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("token_vault")],
    PROGRAM_ID
  );
}

export function getUserAllocationPDA(wallet: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("allocation"), wallet.toBuffer()],
    PROGRAM_ID
  );
}

// ─── On-chain State Types ─────────────────────────────────────────────────────

export interface PresaleStateAccount {
  authority: PublicKey;
  tokenMint: PublicKey;
  tokenVault: PublicKey;
  presaleStart: BN;
  presaleEnd: BN;
  isActive: boolean;
  claimsEnabled: boolean;
  foundingSold: BN;
  earlySold: BN;
  publicSold: BN;
  totalLamportsRaised: BN;
  foundingLamportsPerSprks: BN;
  earlyLamportsPerSprks: BN;
  publicLamportsPerSprks: BN;
  bump: number;
  vaultBump: number;
}

export interface UserAllocationAccount {
  user: PublicKey;
  totalTokens: BN;
  foundingBought: BN;
  earlyBought: BN;
  publicBought: BN;
  claimed: boolean;
  bump: number;
}

// ─── Derived UI State ─────────────────────────────────────────────────────────

export interface PresaleStats {
  isActive: boolean;
  claimsEnabled: boolean;
  activeTier: 0 | 1 | 2;
  tierProgress: [number, number, number]; // [founding%, early%, public%]
  tierSold: [number, number, number];     // displayed SPRKS sold per tier
  totalRaisedSOL: number;
  totalRaisedUSD: number;
  softCapReached: boolean;
}

export function derivePresaleStats(
  state: PresaleStateAccount,
  solPriceUsd: number
): PresaleStats {
  const foundingSold = state.foundingSold.toNumber() / SPRKS_DECIMALS_MULTIPLIER;
  const earlySold = state.earlySold.toNumber() / SPRKS_DECIMALS_MULTIPLIER;
  const publicSold = state.publicSold.toNumber() / SPRKS_DECIMALS_MULTIPLIER;

  const activeTier: 0 | 1 | 2 =
    foundingSold < TIERS[0].supplyDisplayed
      ? 0
      : earlySold < TIERS[1].supplyDisplayed
      ? 1
      : 2;

  const totalLamports = state.totalLamportsRaised.toNumber();
  const totalRaisedSOL = totalLamports / LAMPORTS_PER_SOL;
  const totalRaisedUSD = totalRaisedSOL * solPriceUsd;

  return {
    isActive: state.isActive,
    claimsEnabled: state.claimsEnabled,
    activeTier,
    tierProgress: [
      (foundingSold / TIERS[0].supplyDisplayed) * 100,
      (earlySold / TIERS[1].supplyDisplayed) * 100,
      (publicSold / TIERS[2].supplyDisplayed) * 100,
    ],
    tierSold: [foundingSold, earlySold, publicSold],
    totalRaisedSOL,
    totalRaisedUSD,
    softCapReached: totalRaisedUSD >= 25_000,
  };
}

// ─── SOL Price Fetch ──────────────────────────────────────────────────────────

export async function fetchSolPriceUsd(): Promise<number> {
  try {
    const res = await fetch(
      "https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd",
      { next: { revalidate: 60 } }
    );
    const data = await res.json();
    return data?.solana?.usd ?? 135;
  } catch {
    return 135; // fallback
  }
}

// ─── Buy / Price Helpers ──────────────────────────────────────────────────────

export function sprksForSol(
  solAmount: number,
  lamportsPerSprks: number
): number {
  const lamports = Math.floor(solAmount * LAMPORTS_PER_SOL);
  const raw = (lamports * SPRKS_DECIMALS_MULTIPLIER) / lamportsPerSprks;
  return raw / SPRKS_DECIMALS_MULTIPLIER;
}

export function solForSprks(
  sprksAmount: number,
  lamportsPerSprks: number
): number {
  return (sprksAmount * lamportsPerSprks) / LAMPORTS_PER_SOL;
}
